name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all
    #- name: uncompress test files
    #  run: tar -xvf tests.tar
    - name: Install ValGrind
      run: sudo apt install -y valgrind
    - name: ValGrind
      run: valgrind --error-exitcode=1 --log-file=./log --tool=memcheck --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./compilados/Interprete -t > /dev/null
    - name: ValGrind fallo
      if: failure()
      run: cat log
